### ISSUE TITLE
file VIMModelObject.h doesn't exist

### ISSUE THREAD

**Issue by aklobanov** [vimeo/VIMNetworking#106]
Header file with VIMModelObject interface declaration referenced by many other objects (and imported from many other header files) doesn't exist in this repository.

**Comment by alfiehanssen** [comment]
The README outlines this repo's dependencies (available via Cocoapods or Git Submodules): AFNetworking and [VIMObjectMapper](https://github.com/vimeo/VIMObjectMapper)

VIMObjectMapper contains the `VIMModelObject` class...

**Comment by aklobanov** [comment]
1) What about NSError+BaseError .h and .m categories files presented in Networking->ErrorReporting project group but not existed in the corresponding directories?
2) file VIMVideo.h should include at list #import <CoreGraphics/CGGeometry.h>
for CGSize structure definition.

A lot of errors! Did You ever try to build the project?!!

**Comment by alfiehanssen** [comment]
Setup with cocoapods is a breeze. 

Setup with submodules is more involved. VIMNetworking needs to be a submodule of your project. And AFNetworking and VIMObjectMapper need to be submodules of VIMNetworking. You'd have to configure this manually on your end. We'll update the docs to be more explicit about this. 

Feel free to contribute when you see room for improvement.
