### ISSUE TITLE
incorrect reporting VIMPrivacy for download (and canAdd)

### ISSUE THREAD

**Issue by aklobanov** [vimeo/VIMNetworking#108]
endPoint for me/feed reports download:true for clip privacy but [(VIMVideo *)video privacy] canDownload] returns nil. The same for canAdd. This is because of error in this method:
```
@implementation VIMPrivacy
#pragma mark - VIMMappable
- (NSDictionary *)getObjectMapping
{
/**
 * AKLobanov error correction: change this NSDictionary
 *   return @{@"canAdd": @"add", @"canDownload" : @"download"};
 *   to next one
 */
    return @{@"add" : @"canAdd", @"download" : @"canDownload"};
}
@end
```

**Comment by huebnerob** [comment]
Ah, thanks for catching that, addressed here: https://github.com/vimeo/VIMNetworking/pull/109
