### ISSUE TITLE
Errors configuring VIMNetworking

### ISSUE THREAD

**Issue by mehuls1013** [vimeo/VIMNetworking#113]
Hello Devs, 

I have integrated VIMNetworking (https://github.com/vimeo/VIMNetworking) to my existing iOS project. After follow all steps, i'm getting following errors:

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-VIMNetworking
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-VIMNetworking is not an object file (not allowed in a library)

![vimnetworkingerrors](https://cloud.githubusercontent.com/assets/13884594/9380315/146f28ec-474d-11e5-9d2a-a1056728096a.png)

i've wandered but didn't get any solution.

What am I missing here? It should be more useful if i get any idea to resolve this errors.

Thanks for the help!

**Comment by alfiehanssen** [comment]
@mehuls1013 hard to tell from this information. We've tested inclusion as a pod extensively and haven't run into this issue. If you can provide more detail we can try to weigh in. Otherwise seems like it might be an issue specific to your project?
