### ISSUE TITLE
Edit metadata not working

### ISSUE THREAD

**Issue by mehuls1013** [vimeo/VIMNetworking#122]
Hello Devs,

I've successfully uploaded video to vimeo by using API V3. Now, i want to set few metadata likes name, description, privacy.view etc to uploaded video.

When i tried with vimeo playground, it get success: https://developer.vimeo.com/api/endpoints/videos#/{video_id}

But in code, i tried following two way but didn't get success.

    NSString *strURL = [NSString stringWithFormat:@"%@videos/%@?access_token=%@&name=%@&description=%@&privacy.view=%@", VIMEO_API_CALL_URL, strVideoID, VIMEO_ACCESS_TOKEN_TEMP, strName, strDescription, strPrivacyView];
    NSURL *URL = [NSURL URLWithString:[strURL stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];

    NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:URL];

    [request setHTTPMethod:@"PATCH"];

and following also,

    NSString *strURL = [NSString stringWithFormat:@"%@videos/%@?access_token=%@", VIMEO_API_CALL_URL, strVideoID, VIMEO_ACCESS_TOKEN_TEMP];
    NSURL *URL = [NSURL URLWithString:[strURL stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]];

    NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:URL];

    [request setHTTPMethod:@"PATCH"];

    [request setValue:@"iOS_QuickTime" forHTTPHeaderField:@"name"];
    [request setValue:@"This video is uploaded via iOS applcation and to perform last step by adding all required metadata." forHTTPHeaderField:@"description"];
    [request setValue:@"nobody" forHTTPHeaderField:@"privacy.view"];

I also tried with [request setValue:@"Bearer #TOKEN" forKey:@"Authorization"]; but it still not giving result.

My Access token has 'public private purchased create edit delete interact upload' scopes.

Please help me for solving this issue. Any help will be more helpful.

Thanks .!!..

**Comment by alfiehanssen** [comment]
Your auth token must be specified in the context of an HTTP header. Not as a query param. 

`[request setValue:@"Bearer XXXXXXXXXXXX" forHTTPHeaderField:@"Authorization"];`

Make sure you have ben granted the `upload` permission via the Vimeo API portal (devs must explicitly grant you permission) and make sure that you have verified the email address associated with your account.

**Comment by mehuls1013** [comment]
Hi Alfie Hanssen,

Thanks for your reply.
I already tried with [request setValue:@"Bearer XXXXXXXXXXXX" forHTTPHeaderField:@"Authorization"]; but its not working.

I'm able to upload videos and also able to assign Album to uploaded video but not able to metadata. Associated email address is also verified. 

Please suggest me to go further with this issue.

**Comment by alfiehanssen** [comment]
It's hard to say without additional code and console output. You can provide this and we can try to help further. 

Alternatively you could just use the upload system built into the SDK.
