### ISSUE TITLE
VIMModelObject.h not found

### ISSUE THREAD

**Issue by samidaik00** [vimeo/VIMNetworking#13]
Installed the SDK correctly, but getting the error about the file VIMModelObject.h which I do not seem to see in the project... (?)

**Comment by alfiehanssen** [comment]
@samidaik00, thanks for writing! 

`VIMModelObject` is a class in the [`VIMObjectMapper`](https://github.com/vimeo/VIMObjectMapper) repo. This repo is a submodule of `VIMNetworking`. Seems like the submodule hasn't been initialized/updated. 

cd into the VIMNetworking directory and run `git submodule init && git submodule update` (and make sure those files are included in your Xcode project). 

That should do the trick, let us know if you have other questions etc.

**Comment by samidaik00** [comment]
Hi, 
Thanks for the quick reply.
I just did what you advised and got the following:

Cloning into 'VIMNetworking/External/VIMObjectMapper'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:vimeo/VIMObjectMapper.git' into submodule path 'VIMNetworking/External/VIMObjectMapper' failed

FYI - I have installed VIMNetworking using the recommended 
git clone --recursive https://github.com/vimeo/VIMNetworking.git

**Comment by alfiehanssen** [comment]
Have you added a private key to your Github account? This is necessary when pulling from a git@github repo URL...

**Comment by alfiehanssen** [comment]
@samidaik00, available all day, holler with questions and we'll be able to reply pretty quickly

**Comment by samidaik00** [comment]
Great thanks! thought i had, but was using a different account. Closing this

**Comment by alfiehanssen** [comment]
BOOM, thank you! :8ball:
