### ISSUE TITLE
'AFNetworking.h' not found when importing into Swift project

### ISSUE THREAD

**Issue by andrewbranch** [vimeo/VIMNetworking#133]
Not sure exactly what is causing this problem. Here are the steps I took; I reproduced in a clean, brand new project.

1. Xcode 7 GM *or* Xcode 7.1 beta -> new Swift iOS project
2. Create a Podfile specifying `use_frameworks!` with VIMNetworking (tried all available versions)
3. `pod install`
4. Close project, reopen xcworkspace as CocoaPods prompts
5. Add `import VIMNetworking` to AppDelegate.swift
6. Build

The build fails with `'AFNetworking.h' not found` in VIMRequestOperationManager.h, which consequently gives me `Could not build Objective-C module 'VIMNetworking'`.

The *really* weird thing is, I can switch targets to VIMNetworking and build, and it succeeds.

I am not 100% sure this is not a CocoaPods issue, but I’ve tried installing with multiple versions of CocoaPods, and other Objective C libraries continue to work fine through it. For example, after installing VIMNetworking through CocoaPods, I can `import AFNetworking` and `import VIMObjectMapper` just fine.

**Comment by alfiehanssen** [comment]
@andrewbranch Thanks for filing this, we aren't using `use_frameworks` internally and thus haven't tested this. My guess is that there's some additional configuration we would need to do to support `use_frameworks`. We can explore what's involved or please feel free to make a PR.

**Comment by andrewbranch** [comment]
I’m definitely not experienced enough with the internals of how frameworks communicate to be very useful here. It seems totally opaque to me, as some other libraries Just Work as frameworks. Just wanted to let you all know, as probably most Swift users will be using CocoaPods with `use_frameworks`.

**Comment by alfiehanssen** [comment]
@andrewbranch, 

Got some more info on this one:

Cocoapods `use_frameworks! podfile command changes how pods are built. Without `use_frameworks!` they're compiled into static libraries and with it they're compiled into dynamic frameworks. 

If using the frameworks approach, you must now reference files in those frameworks using framework syntax. E.g. `#import <AFNetworking/AFNetworking.h>` when you're in an Objc file. If you change the lines your project is complaining about accordingly your project should compile. This would mean changing the VIMNetworking code itself. 

Here's where we run into a snag. The Vimeo iOS app supports iOS 7. But dynamic frameworks were introduced in iOS8 and do not work with iOS7. I'm fairly certain that this means we can't modify the libraries to support `use_frameworks!` until we drop support for iOS7 in the Vimeo iOS App. 

The solution for now might be to setup a fork of the sdk where you modify the necessary set of `#import` statements in the sdk to be framework imports.

**Comment by alfiehanssen** [comment]
cc @huebnerob @ghking @victusfate @mikelow

**Comment by alfiehanssen** [comment]
Closing this for now. When we drop support for iOS7 we'll revisit and support `use_frameworks`

**Comment by majia144119** [comment]
which the right answer!
