### ISSUE TITLE
Incorrect documentation Initialization process in README.md file

### ISSUE THREAD

**Issue by aklobanov** [vimeo/VIMNetworking#138]
README.md says that property `config.keychainAccessGroup` of the `VIMSessionConfiguration` is optional. It is not true. Really VIMSessionConfiguration isValid method always check that that this property is not nil. Never in the documentation is said that this property should be equal to keychain group id added to the app's entitlements file. Usually it should be AppIdetifierPrefix.bundleIdentifier from the provisioning profile of the application. I've found that You recommended using KeychainUtiltity class to configure this KeychainService and KeychainAccessGroup parameters. But never is said that now this class is renamed to `VIMKeychain`. I think You should 1) correct documentation or 2) correct method - `(void)authenticationCompleteWithAccount:(VIMAccountNew *)account error:(NSError *)error key:(NSString *)key completionBlock:(VIMErrorCompletionBlock)completionBlock`
for example remove NSAssert  after  
`BOOL success = [VIMAccountStore saveAccount:account forKey:key];`
`NSAssert(success, @"Unable to save account for key: %@", key);`

P.S. I'm using Xcode 7.0 (7A220) and testing on iOS 8.4.1 and 9.0 project target version is 8.0

**Comment by appcelerate** [comment]
+1

**Comment by alfiehanssen** [comment]
Thanks for bringing this to our attention. A fix and revised documentation is included in this PR: 

https://github.com/vimeo/VIMNetworking/pull/147
