### ISSUE TITLE
Not the latest version of the AFNetworking in pod file

### ISSUE THREAD

**Issue by aklobanov** [vimeo/VIMNetworking#139]
Please correct the pod config to the latest version of the AFNetworking. Now is 2.5.4 but the latest is 2.6.0

**Comment by alfiehanssen** [comment]
The newest release upgrades to AFNetworking 2.6.1, note that the upload library was split out into a standalone repo here: https://github.com/vimeo/VIMUpload

**Comment by aklobanov** [comment]
👍
