### ISSUE TITLE
Request multiple videos

### ISSUE THREAD

**Issue by Gamec** [vimeo/VIMNetworking#163]
I have few IDs, how can I request all of them? I saw "Collection request" in readme, but urlPath is `descriptor.urlPath = @"/me/videos";` there. How should it look like to request for example 4 videos with known ids?

**Comment by huebnerob** [comment]
Hi @Gamec,

If these videos are not part of an existing list (watch later, channel, search query, etc.) then you'll need to fetch the videos individually, with several separate requests.  I might recommend you instead add these videos to an album on the signed in account, then request the videos in that album as described here: https://developer.vimeo.com/api/endpoints/users#/{user_id}/albums
