### ISSUE TITLE
How to delete video from vimeo account with VIMNetworking?

### ISSUE THREAD

**Issue by coneits** [vimeo/VIMNetworking#194]
Hello.
I have used this library to get some informations from my vimeo account.
But now, I want to remove a video from vimeo on my iphone app.

***HOW to remove the video from vimeo with this library?***

Looking forward to hearing some advices.
Thanks.

**Comment by alfiehanssen** [comment]
Check out the `deleteVideo` method here: 

https://github.com/vimeo/VIMNetworking/blob/v6.0.2/VIMNetworking/Networking/VimeoClient/VIMClient.h#L100

Also, we've published a new Swift networking library: 

https://github.com/vimeo/VimeoNetworking

We'll be deprecating / not supporting VIMNetworking...
