### ISSUE TITLE
Feature request - tvOS support

### ISSUE THREAD

**Issue by nicolasabric** [vimeo/VIMNetworking#195]
#### Issue Summary
Hi guys, 

First of all thank you for all Viemo libraries really appreciate those. Unfortunately for my current tvOS project I won't be able to use VIMNetworking as tvOS support seems to be missing. If I am not mistaken, as of today, VIMNetworking cannot be used for tvOS whereas VIMVideoPlayer is already compatible. Hence my question is there any plan to make VIMNetworking compatible too?

#### Reproduction Steps
- In your tvOS project adds pod dependency to latest VIMNetworking
- Use the command pod install

#### Expected Behavior
Dependency should be added to the tvOS project.

#### Actual Behavior
Dependency is not added as VIMNetworking is compatible with ios only. 

After a bit of digging I was able to install the dependency to my tvOS project by modifying the podspec in 2 ways:
- Adding the missing tvos.deployment_target and 
- Bumping the version of AFNetworking to 3.1.0

Unfortunately things are never that easy and VIMNetworking is now incompatible with AFNetworking (as 3.x introduced some significant changes). With my current understanding of VIMNetworking and AFNetworking I don't feel confident enough to refactor the library but maybe that something you can do.

**Comment by alfiehanssen** [comment]
Hey @nicolasabric, thank you for writing!

We encountered this very same issue and decided it was time for a change, so we (in particular @huebnerob) developed this cool new Swift version of the Vimeo iOS SDK: 

https://github.com/vimeo/VimeoNetworking

We're still developing it, but it's definitely got enough functionality and documentation to get started doing just about everything that VIMNetworking does. 

Let us know if you have questions, thanks again for writing.

**Comment by nicolasabric** [comment]
Stupid me! Thanks for the very quick reply, will use it right away ;)

**Comment by alfiehanssen** [comment]
Awesome, not stupid at all, we haven't really publicized it because we're still putting the finishing touches on it. Please feel free to file issues or make pull requests.
