### ISSUE TITLE
Build Errors on project with pre-existing AFNetworking cocoapod

### ISSUE THREAD

**Issue by robmontesinos** [vimeo/VIMNetworking#38]
MY project is no longer building after adding VIMNetworking - error is "Redefinition of 'AFNetworkReachabilityStatus' plus nine other errors on AFNetworkingReachabilityManager.

I tried to delete 'AFNetworking' from Podfile to no avail. Cocoa pods didn't remove the AFNetworking cocoa pods. I'm excited to implement VIMNetworking but it has knocked me out. Any suggestions or ideas would be appreciated.

**Comment by alfiehanssen** [comment]
@robmontesinos Thanks for your patience, I just pushed cocoapods support to the `dev` branch and updated the README. Let us know if you have questions and feel free to submit pull requests :+1:
