### ISSUE TITLE
Having trouble getting API results

### ISSUE THREAD

**Issue by robmontesinos** [vimeo/VIMNetworking#42]
I'm not sure what I'm doing wrong but here is the code that I'm using.
The NSLog statement returns: "VIMServerResponse result: (null)"
Any help would be greatly appreciated - client is starting to get nervous.

```Objective-C
// called from AppDelegate didFinishLaunchingWithOptions:
- (void)configureVimeo {
    VIMSessionConfiguration *config = [[VIMSessionConfiguration alloc] init];
    config.clientKey = kVimeoClientIdentifier;
    config.clientSecret = kVimeoClientSecret;
    config.scope = @"private public";
    
    [[VIMSession sharedSession] setupWithConfiguration:config
                                       completionBlock:^(BOOL success) {
                                           NSLog(@"VIMSession setup success? %d", success);
                                       }
     ];
}

// authenticate - called in previous tableView controller prior to arriving at videos list tableview controller
- (void)authenticateVimeo {
    NSLog(@">>> Entering %s <<<", __PRETTY_FUNCTION__);
    
    if ([[VIMSession sharedSession].account isAuthenticated] == NO) {
        [[VIMAPIClient sharedClient] authenticateWithClientCredentialsGrant:^(NSError *error) {
            if (error == nil){
                NSLog(@"Success!");
            } else {
                NSLog(@"Failure: %@", error);
            }
        }];
    } else {
        NSLog(@"-->Vimeo Session isAuthenticated: %d", [[VIMSession sharedSession].account isAuthenticated]);
    }
}

// in videosListViewController I use:

- (void)fetchVideos {
    __weak typeof(self)weakSelf = self;
        
    VIMRequestDescriptor *descriptor = [[VIMRequestDescriptor alloc] init];
//    descriptor.urlPath = [NSString stringWithFormat:@"/me/albums/%@/videos", self.channel.vimeoAlbumID];
    descriptor.urlPath = @"/me/videos";
    descriptor.modelClass = [VIMVideo class];
    descriptor.modelKeyPath = @"data";
    descriptor.cachePolicy = VIMCachePolicy_TryNetworkFirst;

    [[VIMAPIClient sharedClient] fetchWithRequestDescriptor:descriptor
                                            completionBlock:^(VIMServerResponse *response, NSError *error) {
                                                NSLog(@"VIMServerResponse result: %@", response.result);
                                                if (!error) {
                                                    NSArray *videos = (NSArray *)response.result;
                                                    for (VIMVideo *video in videos) {
                                                        [weakSelf.videosList addObject:video];
                                                    }
                                                    [weakSelf.tableView reloadData];
                                                } else {
                                                    NSLog(@"ERROR: %@", error.localizedDescription);
                                                }
                                                
                                            }
     ];
}

**Comment by alfiehanssen** [comment]
You should be able to do some debugging to figure out what's going on, breakpoints, NSLogs, API docs etc. Pretty confident that these mechanisms are working as expected since they drive networking in the Vimeo iOS app.

**Comment by robmontesinos** [comment]
Thank you again @alfiehanssen - that's the road I'm on. 
The most common error I'm getting is:
VideosListViewController fetchVideos]_block_invoke) (VideosListViewController.m:141) ERROR: The operation couldn’t be completed. (NSURLErrorDomain error -1012.)  -1012 is kCFURLErrorUserCancelledAuthentication

At first I thought it was an authentication issue but no problem there (I think) - 

        NSLog(@"-->Vimeo Session isAuthenticated: %d", [[VIMSession sharedSession].account isAuthenticated]);

returns:
[ChaptersListViewController authenticateVimeo]) (ChaptersListViewController.m:102) -->Vimeo Session isAuthenticated: 1

Could it be the digicert-root.cer?

**Comment by alfiehanssen** [comment]
Hey @robmontesinos, got your other email. Can you describe what you're trying to achieve? Are you trying to access a user's private videos? 

The sequence of method calls you should make on app launch is:

1. `setupWithConfiguration`
2. In the completion block of `setupWithConfiguration` check if authenticated and if not call `authenticateWithClientCredentialsGrant`. Same flow as in Pegasus but with credentials grant instead of code grant.
3. If that succeeds you are good to go. You'll be using a client credentials grant token which will give you access to public content only. Accessing private user-specific info can only happen if the user authenticates. 

You will also either need to add the `.cer` file to your app's main bundle or you will need to disable AFNetworking's cert pinning (not preferred, this should not be necessary).

Also worth noting is that you can't set the auth token directly, not sure if this is what you were trying. 

Good luck

**Comment by robmontesinos** [comment]
Thank you @alfiehanssen 

The big picture is to have the client's private videos viewable only through an Phone App without their logging into Vimeo or having a Vimeo account since that would disrupt the user experience. The only videos shown/listed would be those of the client, not the user.

First step is to list the videos by album - right now I am just using "/me/videos" to get a simple response

Step 1 and 2 are done. [[VIMSession sharedSession].account isAuthenticated] returns TRUE

The dogcart-root.cer is in the App Bundle.

I'm not messing with the access token.

The request returns "ERROR: The operation couldn’t be completed. (NSURLErrorDomain error -1012.)" using [[VIMAPIClient sharedClient] fetchWithRequestDescriptor:completionBlock:

I haven't even gotten to the point of trying to play the video, just trying to list them in a tableview.

The app will not be doing any uploading so do I have to also use the KeychainUtility?

How do you suggest I approach displaying a list of private videos and then playing them? We purchased the Pro Account because we saw that it was not possible on the Plus or Free accounts.

**Comment by robmontesinos** [comment]
I just saw this - does this make a difference?

Encoding
Vimeo expects all data to be UTF-8-encoded and will respond with UTF-8-encoded data. Make sure you encode your data as UTF-8 to avoid errors.

VIMOAuthAuthenticator.m - line 112
```Objective-C
     - (NSOperation *)authenticateAccount:(VIMAccount *)account parameters:(NSDictionary *)params completionBlock:(void (^)(id responseObject, NSError *error))completionBlock {
       // Set basic auth header
        NSString *tokenString = [NSString stringWithFormat:@"%@:%@", self.clientID, self.clientSecret];
        
        NSData *plainData = [tokenString dataUsingEncoding:NSUTF8StringEncoding];
        NSString *base64String = [plainData base64EncodedStringWithOptions:0];

        NSString *authHeader = [NSString stringWithFormat:@"Basic %@", [base64String stringByReplacingOccurrencesOfString:@"\r\n" withString:@""]];
        [client.requestSerializer setValue:authHeader forHTTPHeaderField:@"Authorization"];

**Comment by robmontesinos** [comment]
How are Personal Access Tokens incorporated into VIMNetworking in order to pull info about videos, albums, etc. as well as play video?

<h3>Authenticated Requests</h3>

"First you need an access token. Single user applications can find this on their app page, Multi-user applications must generate these tokens. Once you have an access token, you send them through the authorization header"

    curl -H "Authorization: bearer <OAUTH_TOKEN>" https://api.vimeo.com

**Comment by alfiehanssen** [comment]
Hey @robmontesinos, please create unique issues for each distinct issue. Seems like we're talking about a few different things here. 

Currently there's no support for setting the `[VIMSession sharedSession].account` and by extension the account credential. Feel free to pull request this though. 

The encoding thing you mention above is likely not causing the issue you're seeing. Encoding is set up properly.

**Comment by robmontesinos** [comment]
@alfiehanssen  I started from scratch and am getting the data I needed from the Vimeo API (PRO Account) using AFNetworking and parsing the JSON myself.
