### ISSUE TITLE
Having trouble in uploading video

### ISSUE THREAD

**Issue by vivekCZ** [vimeo/VIMNetworking#43]
Hello In my app I am uploading user's video to their vimeo account.

I am getting following error while uploading video to vimeo:

Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo=0x170c77e80 {NSErrorFailingURLStringKey=https://api.vimeo.com/me/videos, NSLocalizedDescription=cancelled, NSErrorFailingURLKey=https://api.vimeo.com/me/videos}

Here is my code sturcture.

In appdelegate file:

       VIMSessionConfiguration *config = [[VIMSessionConfiguration alloc] init];
         config.clientKey = @"client_key";
         config.clientSecret = @"secrete_key";
         config.scope = @"private public create upload";
   
        [[VIMSession sharedSession] setupWithConfiguration:config completionBlock:^(BOOL success)
         {
          [VIMUploadTaskQueue sharedAppQueue];
      
          NSLog(@"VIMSession setup success %d", success);
         }];

      - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:   (NSString *)sourceApplication annotation:(id)annotation
      {
           [[VIMAPIClient sharedClient] authenticateWithCodeGrantResponseURL:url completionBlock:^(NSError *error)
           {
               if (error == nil)
              {
 
                     [[NSNotificationCenter defaultCenter] postNotificationName:@"vimeoUrlAuthenticationSuccess" object:nil];
              
           }
          else
          {
 
              
          }
          
      }];
return YES;
}

while in sharevideo file I have written this code on share button tap event:

 [[VIMAPIClient sharedClient] authenticateWithClientCredentialsGrant:^(NSError *error) {
         
         if (error == nil)
         {
            NSURL *URL = [[VIMAPIClient sharedClient] codeGrantAuthorizationURL];
            [[UIApplication sharedApplication] openURL:URL];
         
         }
         else
         {
            NSLog(@"Failure: %@", error);
         }
         
      }];

now when user returns in app delegate open url method. It will post notification and it will call upload video method.

      - (void)uploadVideoAssets
    {
        AVURLAsset *urlAsset = [[AVURLAsset alloc]initWithURL:updatedVideoURL options:nil];
   
        VIMVideoAsset *videoAsset = [[VIMVideoAsset alloc]initWithURLAsset:urlAsset      canUploadFromSource:YES];
         [[VIMUploadTaskQueue sharedAppQueue] uploadVideoAssets:@[videoAsset]];
     }

**Comment by vivekCZ** [comment]
at the end I got this log instead of error.:

SAVING: {
    tasks =     (
        "<VIMUploadTask: 0x157f8e80>"
    );
}
2015-06-06 17:36:47.108 MyApp[1353:180547] server start (/me)
2015-06-06 17:36:47.592 MyApp[1353:180545] server success 0.484543 sec (/me)

**Comment by alfiehanssen** [comment]
Looks like you need to add the `.cer` file to your app bundle. Have you done this? Without this file cert pinning will block (cancel) all requests made to the Vimeo servers.

**Comment by alfiehanssen** [comment]
From the `README`: "Add the vimeo-api-root.cer certificate file to your Xcode project. This can be found in VIMNetworking/Networking/Certificate/digicert-root.cer. This is necessary to enable certificate pinning."

**Comment by alfiehanssen** [comment]
Just added cert to Pegasus project to prevent any future confusion.

**Comment by vivekCZ** [comment]
I have completed video uploading through API in postman. It is working fine
but when I called same service from project it is giving me error.
