### ISSUE TITLE
VIMVideoAsset Error

### ISSUE THREAD

**Issue by alexandrenascimento** [vimeo/VIMNetworking#49]
When I use the code:
```
NSURL *URL = [assetExportSession outputUrl];
            AVURLAsset *URLAsset = [AVURLAsset assetWithURL:URL];
            VIMVideoAsset *videoAsset = [[VIMVideoAsset alloc] initWithURLAsset:URLAsset];
            [[VIMUploadTaskQueue sharedExtensionQueue] uploadVideoAssets:@[videoAsset]];
```

Returns an error: "No visible @interface for 'VIMVideoAsset' declares the selector 'initWithURLAsset' "

**Comment by alfiehanssen** [comment]
The method name changed, quick fix: look at the header and use the new, similarly named method, will update docs this week.

**Comment by alfiehanssen** [comment]
README has been updated.
