### ISSUE TITLE
Swift Compatibaility

### ISSUE THREAD

**Issue by hammyhamza** [vimeo/VIMNetworking#50]
Its not calling method **VIMAPIClient.sharedClient().fetchWithRequestDescriptor:descriptor**

**Comment by alfiehanssen** [comment]
Please provide more detail on the issue you're encountering. Also feel free to make a pull request.

**Comment by hammyhamza** [comment]
Working fine with objective-C

**Comment by alfiehanssen** [comment]
Closing. Need more info.
