### ISSUE TITLE
Safari Didn't Redirect

### ISSUE THREAD

**Issue by Adnan-Synapps** [vimeo/VIMNetworking#62]
I have open authorised url in safari  after clicking on allow it will show me this popup alert.

![ios simulator screen shot 17-jun-2015 12 23 10 pm](https://cloud.githubusercontent.com/assets/12710071/8201560/ae9b9566-14eb-11e5-98b8-aa24866a37a5.png)

**Comment by huebnerob** [comment]
It looks like iOS is not recognizing the URL scheme used for the oauth code grant response.  Do you have the URL scheme properly registered in your target settings? See this section of the readme for reference: https://github.com/vimeo/VIMNetworking#oauth-authorization-code-grant

**Comment by Adnan-Synapps** [comment]
Hi Got it thanks, yes there is an issue in url scheme at my side
