### ISSUE TITLE
Already has user token, not redirect site needed

### ISSUE THREAD

**Issue by alexandrenascimento** [vimeo/VIMNetworking#64]
The authorization works like this:

1 - Authenticate the app with the client key and secret
2 - Redirect to the site for user login to catch the user token

Proceed?

My webservice already give me the user token for upload video. What can i do in this situation in the second step?

**Comment by alfiehanssen** [comment]
Hey @alexandrenascimento, can you clarify the question a bit? Tough to understand what you're asking and if there is a problem. 

In order to upload a video you must have the user log in to their Vimeo account via the webview redirect flow: https://developer.vimeo.com/api/authentication#generate-redirect

**Comment by alexandrenascimento** [comment]
Ok, my app upload a video to an user account.
I already have:
- client key
- client secret
- user token

Because I already have the user token, is necessary make the login via the webview redirect flow?
If not, how I set the token for not make the redirect?

**Comment by alexandrenascimento** [comment]
Hi @alfiehanssen ! Did you understand my question?

**Comment by alfiehanssen** [comment]
Yes, 

We've made some changes on `dev` branch recently to support this. So you'll have to point at `dev`. Then create a `VIMAccount`, set your token etc on it, and use this method on `VIMSession`:

`- (BOOL)changeAccount:(VIMAccountNew *)account`

To make that account the current account. 

See updated README on `dev` branch. 

This functionality hasn't been tested extensively. Let us know if you have questions. Also feel free to make a PR.

**Comment by alexandrenascimento** [comment]
Do you updated de README file on dev branch?
I'm getting some erros in my code now:
```
    VIMAccountNew *account = [[VIMAccountNew alloc] init];
    account.accessToken = @"<TOKEN_VIMEO>";
    account.scope = @"private public upload";
    [[VIMSession sharedSession] changeAccount:account];
```
error:

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid session ID'
```

**Comment by alfiehanssen** [comment]
We'll add this functionality. It's slated for next sprint: 8/3 - 8/21.

**Comment by ukudala** [comment]
Any update here @alfiehanssen? Excited that it is currently in dev; +1 for this functionality, will be quickly implemented on our end when ready.

**Comment by alfiehanssen** [comment]
@ghking please append info to this issue, with links to updated README, when your PR is complete / merged, :cake:

**Comment by ghking** [comment]
Hi guys, to use an existing token without going through the web flow, you can implement the authorizationHeaderValue: method of VIMRequestOperationManagerDelegate and assign your class as VIMClient's delegate. I've added a new initializer to VIMClient for more easily making a standalone instance.

https://github.com/vimeo/VIMNetworking/tree/5.5.5#json-request

```Objective-C

self.client = [[VIMClient alloc] initWithDefaultBaseURL];
self.client.delegate = self;
[self.client requestURI:@"/videos/77091919" completionBlock:^(VIMServerResponse *response, NSError *error)
{
    id JSONObject = response.result;
    NSLog(@"JSONObject: %@", JSONObject);
}];

# pragma mark - VIMRequestOperationManagerDelegate

- (NSString *)authorizationHeaderValue:(nonnull VIMRequestOperationManager *)operationManager
{
    return [NSString stringWithFormat:@"Bearer <TOKEN>"];
}

```

**Comment by alfiehanssen** [comment]
@ukudala Check out the revised README on master branch. This should address your needs. Revised since @ghking's comment above. Let us know if not. Thanks.
