### ISSUE TITLE
Error uploading video

### ISSUE THREAD

**Issue by carsonperrotti** [vimeo/VIMNetworking#65]
Hi there, I'm having an issue uploading a video to vimeo. I am able to authenticate a user, but during the upload process, it fails with these errors.

`Reponse did not include upload_link_secure or complete_uri. ((null))`

What am I missing here? I made sure that I included the crt in my project as well. 

Thanks for the help!

Error in more detail:

`2015-06-23 18:48:19.073 irys[676:92936] SAVING: {
    tasks =     (
        "<VIMUploadTask: 0x158472250>"
    );
}
2015-06-23 18:48:19.074 irys[676:92936] --NEXT
2015-06-23 18:48:19.076 irys[676:92936] SAVING: {
    tasks =     (
    );
}
2015-06-23 18:48:19.078 irys[676:92936] --UPLOAD started
2015-06-23 18:48:19.079 irys[676:92936] --CREATE started
2015-06-23 18:48:19.091 irys[676:92936] SAVING: {
    tasks =     (
    );
}
2015-06-23 18:48:19.681 irys[676:92936] --sessionTaskDidComplete
2015-06-23 18:48:19.682 irys[676:92936] SAVING: {
    tasks =     (
    );
}
2015-06-23 18:48:19.684 irys[676:92936] --CREATE failed Error Domain=VIMCreateRecordTaskErrorDomain Code=0 "Reponse did not include upload_link_secure or complete_uri. ((null))" UserInfo=0x15853af80 {NSLocalizedDescription=Reponse did not include upload_link_secure or complete_uri. ((null))}
2015-06-23 18:48:19.689 irys[676:92936] SAVING: {
    tasks =     (
    );
}
2015-06-23 18:48:19.693 irys[676:92936] --UPLOAD failed Error Domain=VIMCreateRecordTaskErrorDomain Code=0 "Reponse did not include upload_link_secure or complete_uri. ((null))" UserInfo=0x15853af80 {NSLocalizedDescription=Reponse did not include upload_link_secure or complete_uri. ((null))}
2015-06-23 18:48:19.694 irys[676:92936] --NEXT 0: queue complete!
`

**Comment by alfiehanssen** [comment]
Hey @carsonperrotti, thanks for posting this issue, interesting that you're getting a 200 status code and no NSError but the response doesn't include this info. Does this happen when you initiate an upload with the app in the foreground and keep the app in the foreground until the upload completes? Or does this occur when the app is backgrounded for a period of time during the upload?

**Comment by carsonperrotti** [comment]
It occurs when the app is in the foreground. It seems to fail fairly quickly after starting the upload and not during the process. Is there any further info you need from me to find out what's going on here? Happy to get you any info you may need.

**Comment by carsonperrotti** [comment]
Any suggestions for a solution to this bug @alfiehanssen? Thanks.

**Comment by alfiehanssen** [comment]
@carsonperrotti, 

Can you send us more information about the response that you're getting? Set some breakpoints inside VIMCreateTicketTask and send as much info as you can. Including response object / string. If you're able to snoop the request using Charles Proxy or similar and send info from that it would be helpful too. 

Also just to confirm, the "app" you set up in the Vimeo dev portal has the upload permission? And you've configured VIMNetworking properly with the appropriate scope, client id/secret, background session ID?

cc @Dashron

**Comment by carsonperrotti** [comment]
I added some breakpoints in VIMCreateTicketTask. initWithURLAsset gets called, sets _urlAsset and identifier. ```file:///private/var/mobile/Containers/Data/Application/A258AB8A-A30C-42E5-A8C9-7607FA80DCC5/tmp/irys_20150623-164729.MOV```

Then, it jumps into the 'resume' method and posts ```[VIMTaskQueueDebugger postLocalNotificationWithContext:self.sessionManager.session.configuration.identifier message:[NSString stringWithFormat:@"%@ started", self.name]];```

fullURL gets set to ```/me/videos -- https://api.vimeo.com/```
fileSize gets set to ```878081```

urlRequest gets set with the url of ```https://api.vimeo.com/me/videos```
value gets set to ```Bearer 0ede8ead163e00e3c4cce259dba9fffb```
resume is called on task

encodeWithCoder is called:
self.localURI, uploadURI, activationURI and responseDictionary are all nil.
self.urlasset.url has the file path

setupTaskDidComplete is called
error is nil,
task réponse is ```<NSHTTPURLResponse: 0x137620c20> { URL: https://api.vimeo.com/me/videos } { status code: 403, headers {
    "Accept-Ranges" = bytes;
    "Cache-Control" = "no-cache, max-age=315360000";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 78;
    "Content-Type" = "application/vnd.vimeo.error+json";
    Date = "Fri, 26 Jun 2015 18:44:38 GMT";
    Expires = "Mon, 23 Jun 2025 18:44:38 GMT";
    Server = nginx;
    "Strict-Transport-Security" = "max-age=900; includeSubDomains";
    Vary = "Accept,Vimeo-Client-Id,Accept-Encoding";
    Via = "1.1 varnish";
    "X-Cache" = MISS;
    "X-Cache-Hits" = 0;
    "X-Served-By" = "cache-ord1729-ORD";
    "X-Timer" = "S1435344278.804049,VS0,VE72";
} }```

sessionManager taskDidComplete gets called, error is nil and task.response has the same response as above.
uploadURI & activationURI are nil

didSucceed returns NO

**Comment by alfiehanssen** [comment]
Awesome, what about the response body? It should contain a string returned from Vimeo servers that indicates what specifically went awry....

NSHTTPURLResponse...

**Comment by carsonperrotti** [comment]
Forgive me if I'm missing something obvious here. I am seeing the task response be a NSURLResponse class. I am not sure how to get the body of that response. Any tips?

**Comment by carsonperrotti** [comment]
I think I found the response body is just ```Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: forbidden (403)" UserInfo=0x12584d4c0 {com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x128196640> { URL: https://api.vimeo.com/me/videos } { status code: 403, headers {
    "Accept-Ranges" = bytes;
    "Cache-Control" = "no-cache, max-age=315360000";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 78;
    "Content-Type" = "application/vnd.vimeo.error+json";
    Date = "Fri, 26 Jun 2015 19:37:42 GMT";
    Expires = "Mon, 23 Jun 2025 19:37:42 GMT";
    Server = nginx;
    "Strict-Transport-Security" = "max-age=900; includeSubDomains";
    Vary = "Accept,Vimeo-Client-Id,Accept-Encoding";
    Via = "1.1 varnish";
    "X-Cache" = MISS;
    "X-Cache-Hits" = 0;
    "X-Served-By" = "cache-ord1723-ORD";
    "X-Timer" = "S1435347462.837042,VS0,VE50";
} }, NSErrorFailingURLKey=https://api.vimeo.com/me/videos, com.alamofire.serialization.response.error.data=<>, NSLocalizedDescription=Request failed: forbidden (403)}```

**Comment by carsonperrotti** [comment]
Also tried sniffing the traffic with Charles, but it's SSL encrypted. @alfiehanssen Any suggestions?

**Comment by Dashron** [comment]
The key part there is the 403 actually. This likely means that the token you are using is either invalid, or a clientCredentials token. Client credentials are not authenticated, and won't work on any `/me` request.

If you contact us at vimeo.com/help/contact we can validate the token for you, or you can debug further by requesting another endpoint with that token (such as `/users/dashron/videos`). If the other endpoint works, the token is client credentials, if the endpoint does not work it's an invalid token

**Comment by carsonperrotti** [comment]
Thank you @Dashron I will try that out.

**Comment by carsonperrotti** [comment]
Can you guys confirm these steps with me? I'm so stuck on this I'm going all the way back to the basics here.

config.clientKey  is Client Identifier on the api portal
config.clientSecret  is Client Secrets on the api portal.
scope is set to "private public interact  create upload"

After a user authenticates with authenticateWithCodeGrantResponseURL i am able to start uploading videos to the users account? Are there any steps I'm missing along the way?

**Comment by alfiehanssen** [comment]
@carsonperrotti, here is a checklist of items, let us know if you've got these covered. 

- [ ] Upload permission granted by Vimeo API team
- [ ] Valid client key/secret pair and proper scope (scope includes upload)
- [ ] You specify a `config.backgroundSessionIdentifierApp = @"YOUR SESSION ID";`
- [ ] You're authenticating a user 
- [ ] When the user is authenticated you're uploading a video (VIMSession account is a user account and not a client credentials account)
- [ ] You're setting `[VIMUploadSessionManager sharedAppInstance].completionHandler = completionHandler;` in AppDelegate

Also, where are you based, NYC by chance? Really wanna get this working for you.
And, where are you getting your asset from? Device camera roll?
And, are you uploading from app, extension or both?

**Comment by Dashron** [comment]
Update for future reference. @carsonperrotti provided me an access token through our help portal, https://vimeo.com/help/contact. I checked this access token and discovered the user had not verified the email address on their account.

If anyone encounters an uploading error in the future that matches this, first make sure you can upload on site. If you can, contact us with your access token so we can learn more!
